### ISSUE TITLE
Sorting is wrong on display

### ISSUE THREAD

**Issue by conconnl** [joomla-extensions/pkg_languagepack#71] opened 2021-08-20 07:53 UTC
https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-english-australia

The version number sort is wrong on the package download list.
Version 4.0.1.1. should be at the top.

<img width="723" alt="image" src="https://user-images.githubusercontent.com/11913918/130199569-7cd2dae7-2b57-4123-8d4b-883911e176d7.png">

CC @particthistle

**Comment by wilsonge** [comment] 2021-08-24 21:43
This is the ARS View. I don't have control over the ordering from this component as far as I know

**Comment by particthistle** [comment] 2021-08-25 05:12
This particular example was caused by me getting up to speed on what's needed to prep a language pack. Learning curve caused a to the upload sequence in trying to resolve the version numbering (now fixed up in 4.0.1.2 en-US).

At the moment it loads the view in the sequence the packs were uploaded, not looking at the version numbering.

In regards to a solution for this issue, the upload routine for language packs prevents you uploading a new pack using an **existing** version number for a language pack. It does not verify whether the language pack version is in the correct sequence compared to previous uploads.

You also can't remove a language pack if you're a proofreader and you find that there's a flaw in your package (typically you have a window of time between uploading it and it becoming available in the installation list. (Ideally this doesn't happen through testing, but as we're about to have a lot of new proofreaders in a short window of time 🤞🏻 it may be worth considering?)

**Comment by MartijnMaandag** [comment] 2021-10-17 08:50
In Joomla 3.x the order is wrong.

**Comment by wilsonge** [comment] 2021-10-17 18:12
I'm going to work on it. Apologies - won't be immediate though - probably around a week as have to figure out the internals of the ARS ordering system

**Comment by HLeithner** [comment] 2022-05-01 09:39
looking at the example it looks fixed, please reopen or create a new issue if still wrong.

**Closed by HLeithner** 2022-05-01 09:39 UTC
